sudo: required
services:
  - docker

before_install:
  - docker build -t pamersielle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pamersielle/react-test npm test -- --coverage

after_success:
  - docker build -t pamersielle/multi-client ./client
  - docker build -t pamersielle/multi-nginx ./nginx
  - docker build -t pamersielle/multi-server ./server
  - docker build -t pamersielle/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pamersielle/multi-client
  - docker push pamersielle/multi-nginx
  - docker push pamersielle/multi-server
  - docker push pamersielle/multi-worker